### ISSUE TITLE
error while run (protocol by the name "dns4" already exists)

### ISSUE THREAD

**Issue by captainchanzxc** [ipfs/dht-node#23]
panic: error registering dns4 protocol: protocol by the name "dns4" already exists

goroutine 1 [running]:
github.com/multiformats/go-multiaddr-dns.init.0()
	/Users/myusrname/go/pkg/mod/github.com/multiformats/go-multiaddr-dns@v0.0.3/dns.go:42 +0x21a
exit status 2

thanks!

**Comment by Stebalien** [comment]
Already fixed in https://github.com/ipfs/dht-node/pull/22.
